### ISSUE TITLE
Error thrown for undefined reference

### ISSUE THREAD

**Issue by SBoudrias** [nodesecurity/gulp-nsp#21]
Not sure why it happens, but this just constantly happen on [yeoman-generator](https://github.com/yeoman/generator), so it really feels like a bug in gulp-nsp.

```
[23:06:04] 'nsp' errored after 5.03 ms
[23:06:04] TypeError: Cannot read property 'length' of undefined
    at /Users/sboudrias/github/yeoman-generator/node_modules/gulp-nsp/index.js:27:45
    at Object.module.exports [as check] (/Users/sboudrias/github/yeoman-generator/node_modules/gulp-nsp/node_modules/nsp/lib/check.js:83:12)
    at rsGulp (/Users/sboudrias/github/yeoman-generator/node_modules/gulp-nsp/index.js:23:7)
    at Gulp.<anonymous> (/Users/sboudrias/github/yeoman-generator/gulpfile.js:34:3)
    at module.exports (/Users/sboudrias/github/yeoman-generator/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/sboudrias/github/yeoman-generator/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/sboudrias/github/yeoman-generator/node_modules/orchestrato


r/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/sboudrias/github/yeoman-generator/node_modules/orchestrator/index.js:134:8)
    at /Users/sboudrias/github/yeoman-generator/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
```

Example live trace on Travis https://travis-ci.org/yeoman/generator/jobs/93897192

**Comment by SBoudrias** [comment]
Ugh, sorry! Looks like I didn't update the gulpfile correctly when I bumped gulp-nsp.

**Comment by evilpacket** [comment]
Thx! If you find other ways we can improve this please let us know.

**Comment by samuellralph** [comment]
I put the proxy and it worked:
File: gulpfile.js

gulp.task('nsp', function (cb) {
  nsp({package: path.resolve('package.json'), proxy:'http://username:password@host'}, cb);
});

[10:21:47] Starting 'nsp'...
[10:21:51](+) No known vulnerabilities found
[10:21:51] Finished 'nsp' after 3.85 s
[10:21:51] Starting 'prepublish'...
[10:21:51] Finished 'prepublish' after 23 µs

**Comment by evilpacket** [comment]
Thanks for the report. I'll try and verify and fix this when I get a free moment today.

**Comment by evilpacket** [comment]
Sorry I didn't realize this wasn't a new issue ha. Glad it's working.
